version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: quickpress-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1heqydnm
      MYSQL_DATABASE: quickpress_db
      MYSQL_USER: quickpress_user
      MYSQL_PASSWORD: quickpass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: